- name: Run using a project directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install pyyaml==5.3.1 python package
      ansible.builtin.pip:
        name: pyyaml==5.3.1
    - name: Install docker-compose python package
      ansible.builtin.pip:
        name: docker-compose
    - name: Install docker==6.1.3 python package
      ansible.builtin.pip:
        name: docker==6.1.3
    - name: Install requests==2.31.0 python package
      ansible.builtin.pip:
        name: requests==2.31.0
    - name: Install flask python package
      ansible.builtin.pip:
        name: flask
